using System;
using System.Collections.Generic;
using TMPro;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Tilemaps;

/// <summary>
/// Represents a building placed on the grid.
/// Handles placement validation, wiring selection, UI indicators,
/// and interaction events such as clicking the building.
/// </summary>
public class Building : MonoBehaviour, IPointerClickHandler
{
    /// <summary>Whether this building has been placed on the grid.</summary>
    public bool Placed { get; set; }

    /// <summary>The area footprint this building occupies on the grid.</summary>
    [SerializeField] public BoundsInt area;

    /// <summary>Income generated by this building (if applicable).</summary>
    [SerializeField] public int income;

    /// <summary>Cost required to place this building.</summary>
    [SerializeField] public int cost;

    /// <summary>World position of the building.</summary>
    public Vector3 buildingPosition = new Vector3(0, 0, 0);

    /// <summary>Grid cell position of the building.</summary>
    public Vector3Int buildingPositionInt;

    /// <summary>
    /// Dictionary used for storing wiring connections
    /// between buildings and their linked nodes.
    /// </summary>
    [SerializeField] public Dictionary<List<string>, List<Node>> nodeConnectionsDictionary =
        new Dictionary<List<string>, List<Node>>(5);

    /// <summary>Types of buildings supported by this class.</summary>
    public enum BuildingType
    {
        House,
        Generator,
        None
    }

    /// <summary>The type of this building.</summary>
    public BuildingType buildingType = BuildingType.None;

    /// <summary>
    /// Whether this building was just spawned. Used for preventing immediate interactions.
    /// </summary>
    public bool recentlySpawned = false;

    /// <summary>
    /// Maximum number of wiring connections this building can support.
    /// </summary>
    public int maxAllowedConnections;

    Tilemap TempTileMap;

    /// <summary>Reference to the GridLayout used for cell conversion.</summary>
    public GridLayout gridLayout;

    /// <summary>Reference to the main GridBuildingSystem manager.</summary>
    public GridBuildingSystem gridBuildingSystem;

    /// <summary>
    /// True if this building is currently connected to power via wiring.
    /// </summary>
    [SerializeField] public bool isConnectedToPower = false;

    /// <summary>UI element displayed above a house showing its income.</summary>
    public GameObject IncomeText;

    /// <summary>UI element displayed above a generator showing number of connections.</summary>
    public GameObject ConnectionText;


    /// <summary>
    /// Checks whether this building can be placed by
    /// verifying that its occupied cells are free.
    /// </summary>
    public bool CanBePlaced()
    {
        Vector3Int positionInt =
            GameObject.Find("Grid")
                .GetComponent<GridBuildingSystem>()
                .gridLayout.LocalToCell(transform.position);

        BoundsInt areaTemp = area;
        areaTemp.position = positionInt;

        return GameObject.Find("Grid")
            .GetComponent<GridBuildingSystem>()
            .CanTakeArea(areaTemp);
    }

    /// <summary>
    /// Placeholder for checking whether the building is connected
    /// to a generator via wiring.
    /// </summary>
    public void CheckPowerConnection()
    {
        // To be implemented
    }

    /// <summary>
    /// Finalizes the placement of this building on the grid,
    /// marking its cell area as occupied.
    /// </summary>
    public void Place()
    {
        Vector3Int positionInt =
            GameObject.Find("Grid")
                .GetComponent<GridBuildingSystem>()
                .gridLayout.LocalToCell(transform.position);

        BoundsInt areaTemp = area;
        areaTemp.position = positionInt;

        Placed = true;

        GameObject.Find("Grid")
            .GetComponent<GridBuildingSystem>()
            .TakeArea(area);
    }


    // --------------------------
    // Unity Lifecycle
    // --------------------------

    void Start()
    {
        gridLayout = GameObject.Find("Grid").GetComponent<GridLayout>();
        gridBuildingSystem = GameObject.Find("Grid").GetComponent<GridBuildingSystem>();

        // Initialize UI elements based on building type
        if (this.buildingType == BuildingType.House)
        {
            IncomeText = this.transform.Find("IncomeText").gameObject;
            IncomeText.SetActive(false);
        }
        else if (this.buildingType == BuildingType.Generator)
        {
            ConnectionText = this.transform.Find("ConnectionText").gameObject;
            ConnectionText.SetActive(false);
        }

        buildingPositionInt =
            gridBuildingSystem.gridLayout.LocalToCell(transform.position);
    }

    void Update()
    {
        // Currently unused, but reserved for future logic
    }


    // --------------------------
    // Interaction Handling
    // --------------------------

    /// <summary>
    /// Called when the player clicks this building.
    /// Handles selection or wiring logic depending on the current action mode.
    /// </summary>
    public void OnPointerClick(PointerEventData eventData)
    {
        // If not in wiring mode: simply select the building
        if (gridBuildingSystem.currentActionType == GridBuildingSystem.CurrentActionType.None)
        {
            GameObject clickedObject = eventData.pointerPress;

            Debug.Log(eventData.pointerPress.name);
            Debug.Log(clickedObject.name + " has been selected!");

            gridBuildingSystem.selectedBuilding = this;
        }

        // Wiring mode logic
        else if (gridBuildingSystem.currentActionType == GridBuildingSystem.CurrentActionType.Wiring)
        {
            Vector2 touchPos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            Vector3Int cellPos = gridLayout.LocalToCell(touchPos);
            GameObject clickedObject = eventData.pointerPress;

            // Selecting the generator first
            if (gridBuildingSystem.selectedGameObjects.Count == 0)
            {
                if (clickedObject.GetComponent<Building>().buildingType != BuildingType.Generator)
                {
                    Debug.Log("Didn't select a generator, returning!");
                    return;
                }

                clickedObject.transform.Find("Sprite")
                    .GetComponent<SpriteRenderer>().color = Color.red;

                gridBuildingSystem.selectedGameObjects.Add(clickedObject);
                gridBuildingSystem.selectedGameObjectsPosition.Add(cellPos);
            }

            // Selecting the house second
            else if (gridBuildingSystem.selectedGameObjects.Count == 1)
            {
                if (clickedObject.GetComponent<Building>().buildingType != BuildingType.House)
                {
                    // Reset original generator highlight
                    gridBuildingSystem.selectedGameObjects[0]
                        .transform.Find("Sprite")
                        .GetComponent<SpriteRenderer>().color = Color.white;

                    Debug.Log("Didn't select a house, returning!");
                    return;
                }

                clickedObject.transform.Find("Sprite")
                    .GetComponent<SpriteRenderer>().color = Color.blue;

                gridBuildingSystem.selectedGameObjects.Add(clickedObject);
                gridBuildingSystem.selectedGameObjectsPosition.Add(cellPos);
            }
        }
    }
}
